Repository Faithful-Resource-Pack/Website, pull requests merged in 2022-01, with the labels that each got.

#38 Add Turkish translation
  about.html
  comments-policy.html
  license.html
  translated/README.md
  translated/about/tr.html
  translated/comments-policy/tr.html
  translated/license/tr.html
Labels: translation

#42 Added Afrikaans language support
  about.html
  comments-policy.html
  license.html
  translated/README.md
  translated/about/za.html
  translated/comments-policy/za.html
  translated/license/za.html
Labels: translation

#47 Added addons socials
  _layouts/default.html
  _layouts/post.html
  about.html
  comments-policy.html
  css/main.scss
  image/addons/curseforge.svg
  index.js
  js/addons/addon-post.js
  js/download/index.js
  js/mods/modpacks.js
  js/mods/mods.js
  js/stats.js
  js/theme.js
  license.html
Labels: enhancement

#45 Chinese Translate + Translate bug fix
  README.md
  about.html
  translated/README.md
  translated/about/cn.html
  translated/license/cn.html
  translated/license/tw.html
Labels: enhancement, translation
